In [1]:
import pandas as pd

In [2]:
bios = pd.read_csv("./Messy_Data/bios.csv")

In [3]:
bios.shape

(145500, 16)

### So we have 145500 rows and 16 columns

In [4]:
bios.head()

,Roles,Sex,Full name,Used name,Born,Died,NOC,athlete_id,Measurements,Affiliations,Nick/petnames,Title(s),Other names,Nationality,Original name,Name order
0,Competed in Olympic Games,Male,"François Joseph Marie Antoine ""Jean-François""•...",Jean-François•Blanchy,"12 December 1886 in Bordeaux, Gironde (FRA)","2 October 1960 in Saint-Jean-de-Luz, Pyrénées-...",France,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Competed in Olympic Games,Male,Arnaud Benjamin•Boetsch,Arnaud•Boetsch,"1 April 1969 in Meulan, Yvelines (FRA)",NaN,France,2,183 cm / 76 kg,"Racing Club de France, Paris (FRA)",NaN,NaN,NaN,NaN,NaN,NaN
2,Competed in Olympic Games • Administrator,Male,Jean Laurent Robert•Borotra,Jean•Borotra,"13 August 1898 in Biarritz, Pyrénées-Atlantiqu...","17 July 1994 in Arbonne, Pyrénées-Atlantiques ...",France,3,183 cm / 76 kg,"TCP, Paris (FRA)",Le Basque Bondissant (The Bounding Basque),NaN,NaN,NaN,NaN,NaN
3,Competed in Olympic Games,Male,Jacques Marie Stanislas Jean•Brugnon,Jacques•Brugnon,"11 May 1895 in Paris VIIIe, Paris (FRA)","20 March 1978 in Monaco, Monaco (MON)",France,4,168 cm / 64 kg,"Sporting club de Paris, Paris (FRA)",Toto,NaN,NaN,NaN,NaN,NaN
4,Competed in Olympic Games,Male,Henry Albert•Canet,Albert•Canet,"17 April 1878 in Wandsworth, England (GBR)","25 July 1930 in Paris VIIe, Paris (FRA)",France,5,NaN,"TCP, Paris (FRA)",NaN,NaN,NaN,NaN,NaN,NaN

### Here we can see that most of the columns have NaN Values

### Lets note down steps on which data needs to be cleaned.

- Get rid of bullet points in Used Names 
- Split height/weight
- Parse out dates from 'Born' & 'Died' column
- Parse out city, region, and country from 'Born' column
- Get rid of extra column
- Converting all column names into Snake Case

Before doing any changes to the dataset, lets make a copy of it and then proceed with the changes.

In [5]:
df = bios.copy()

In [6]:
df.head(10)

,Roles,Sex,Full name,Used name,Born,Died,NOC,athlete_id,Measurements,Affiliations,Nick/petnames,Title(s),Other names,Nationality,Original name,Name order
0,Competed in Olympic Games,Male,"François Joseph Marie Antoine ""Jean-François""•...",Jean-François•Blanchy,"12 December 1886 in Bordeaux, Gironde (FRA)","2 October 1960 in Saint-Jean-de-Luz, Pyrénées-...",France,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Competed in Olympic Games,Male,Arnaud Benjamin•Boetsch,Arnaud•Boetsch,"1 April 1969 in Meulan, Yvelines (FRA)",NaN,France,2,183 cm / 76 kg,"Racing Club de France, Paris (FRA)",NaN,NaN,NaN,NaN,NaN,NaN
2,Competed in Olympic Games • Administrator,Male,Jean Laurent Robert•Borotra,Jean•Borotra,"13 August 1898 in Biarritz, Pyrénées-Atlantiqu...","17 July 1994 in Arbonne, Pyrénées-Atlantiques ...",France,3,183 cm / 76 kg,"TCP, Paris (FRA)",Le Basque Bondissant (The Bounding Basque),NaN,NaN,NaN,NaN,NaN
3,Competed in Olympic Games,Male,Jacques Marie Stanislas Jean•Brugnon,Jacques•Brugnon,"11 May 1895 in Paris VIIIe, Paris (FRA)","20 March 1978 in Monaco, Monaco (MON)",France,4,168 cm / 64 kg,"Sporting club de Paris, Paris (FRA)",Toto,NaN,NaN,NaN,NaN,NaN
4,Competed in Olympic Games,Male,Henry Albert•Canet,Albert•Canet,"17 April 1878 in Wandsworth, England (GBR)","25 July 1930 in Paris VIIe, Paris (FRA)",France,5,NaN,"TCP, Paris (FRA)",NaN,NaN,NaN,NaN,NaN,NaN
5,Competed in Olympic Games,Male,Nicolas•Chatelain,Nicolas•Chatelain,"13 January 1970 in Amiens, Somme (FRA)",NaN,France,6,181 cm / 70 kg,"SAG Cestas, Cestas (FRA)",NaN,NaN,NaN,NaN,NaN,NaN
6,Competed in Olympic Games,Male,Patrick•Chila,Patrick•Chila,"27 November 1969 in Ris-Orangis, Essonne (FRA)",NaN,France,7,180 cm / 73 kg,"AS Pontoise-Cergy TT, Pontoise (FRA) / Royal V...",NaN,NaN,NaN,NaN,NaN,NaN
7,Competed in Olympic Games,Male,Henri Jean•Cochet,Henri•Cochet,"14 December 1901 in Villeurbanne, Rhône (FRA)","2 April 1987 in Saint-Germain-en-Laye, Yveline...",France,8,NaN,NaN,Le Magicien,NaN,NaN,NaN,NaN,NaN
8,Competed in Olympic Games,Male,Marcel•Cousin,Marcel•Cousin,"4 August 1896 in Nîmes, Gard (FRA)","1 August 1986 in Nîmes, Gard (FRA)",France,9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,Competed in Olympic Games,Male,Luc Henri Hervé Guy•Gardye de la Chapelle,Guy•de la Chapelle,"16 July 1868 in Farges-Allichamps, Cher (FRA)",27 August 1923,France,10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### Task-01: Get rid of bullet points in Used Names

As we can see that, column "Used name" has names with specific symbol "•". We want to remove those symbols and separate the names into a new column named "name"

Before that lets check if all the rows have that symbol

In [8]:
len(df)

145500

In [9]:
len(df[df["Used name"].str.contains("•")])

145500

Now lets remove that symbol

In [10]:
df['name'] = df['Used name'].str.replace("•", " ")

In [11]:
df.head()

,Roles,Sex,Full name,Used name,Born,Died,NOC,athlete_id,Measurements,Affiliations,Nick/petnames,Title(s),Other names,Nationality,Original name,Name order,name
0,Competed in Olympic Games,Male,"François Joseph Marie Antoine ""Jean-François""•...",Jean-François•Blanchy,"12 December 1886 in Bordeaux, Gironde (FRA)","2 October 1960 in Saint-Jean-de-Luz, Pyrénées-...",France,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Jean-François Blanchy
1,Competed in Olympic Games,Male,Arnaud Benjamin•Boetsch,Arnaud•Boetsch,"1 April 1969 in Meulan, Yvelines (FRA)",NaN,France,2,183 cm / 76 kg,"Racing Club de France, Paris (FRA)",NaN,NaN,NaN,NaN,NaN,NaN,Arnaud Boetsch
2,Competed in Olympic Games • Administrator,Male,Jean Laurent Robert•Borotra,Jean•Borotra,"13 August 1898 in Biarritz, Pyrénées-Atlantiqu...","17 July 1994 in Arbonne, Pyrénées-Atlantiques ...",France,3,183 cm / 76 kg,"TCP, Paris (FRA)",Le Basque Bondissant (The Bounding Basque),NaN,NaN,NaN,NaN,NaN,Jean Borotra
3,Competed in Olympic Games,Male,Jacques Marie Stanislas Jean•Brugnon,Jacques•Brugnon,"11 May 1895 in Paris VIIIe, Paris (FRA)","20 March 1978 in Monaco, Monaco (MON)",France,4,168 cm / 64 kg,"Sporting club de Paris, Paris (FRA)",Toto,NaN,NaN,NaN,NaN,NaN,Jacques Brugnon
4,Competed in Olympic Games,Male,Henry Albert•Canet,Albert•Canet,"17 April 1878 in Wandsworth, England (GBR)","25 July 1930 in Paris VIIe, Paris (FRA)",France,5,NaN,"TCP, Paris (FRA)",NaN,NaN,NaN,NaN,NaN,NaN,Albert Canet

### Task-02: Split height/weight

In [12]:
df['height_cm'] = df['Measurements'].str.extract(r'(\d+ cm)')
df['weight_kg'] = df['Measurements'].str.extract(r'(\d+ kg)')

In [13]:
df.head(10)

,Roles,Sex,Full name,Used name,Born,Died,NOC,athlete_id,Measurements,Affiliations,Nick/petnames,Title(s),Other names,Nationality,Original name,Name order,name,height_cm,weight_kg
0,Competed in Olympic Games,Male,"François Joseph Marie Antoine ""Jean-François""•...",Jean-François•Blanchy,"12 December 1886 in Bordeaux, Gironde (FRA)","2 October 1960 in Saint-Jean-de-Luz, Pyrénées-...",France,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Jean-François Blanchy,NaN,NaN
1,Competed in Olympic Games,Male,Arnaud Benjamin•Boetsch,Arnaud•Boetsch,"1 April 1969 in Meulan, Yvelines (FRA)",NaN,France,2,183 cm / 76 kg,"Racing Club de France, Paris (FRA)",NaN,NaN,NaN,NaN,NaN,NaN,Arnaud Boetsch,183 cm,76 kg
2,Competed in Olympic Games • Administrator,Male,Jean Laurent Robert•Borotra,Jean•Borotra,"13 August 1898 in Biarritz, Pyrénées-Atlantiqu...","17 July 1994 in Arbonne, Pyrénées-Atlantiques ...",France,3,183 cm / 76 kg,"TCP, Paris (FRA)",Le Basque Bondissant (The Bounding Basque),NaN,NaN,NaN,NaN,NaN,Jean Borotra,183 cm,76 kg
3,Competed in Olympic Games,Male,Jacques Marie Stanislas Jean•Brugnon,Jacques•Brugnon,"11 May 1895 in Paris VIIIe, Paris (FRA)","20 March 1978 in Monaco, Monaco (MON)",France,4,168 cm / 64 kg,"Sporting club de Paris, Paris (FRA)",Toto,NaN,NaN,NaN,NaN,NaN,Jacques Brugnon,168 cm,64 kg
4,Competed in Olympic Games,Male,Henry Albert•Canet,Albert•Canet,"17 April 1878 in Wandsworth, England (GBR)","25 July 1930 in Paris VIIe, Paris (FRA)",France,5,NaN,"TCP, Paris (FRA)",NaN,NaN,NaN,NaN,NaN,NaN,Albert Canet,NaN,NaN
5,Competed in Olympic Games,Male,Nicolas•Chatelain,Nicolas•Chatelain,"13 January 1970 in Amiens, Somme (FRA)",NaN,France,6,181 cm / 70 kg,"SAG Cestas, Cestas (FRA)",NaN,NaN,NaN,NaN,NaN,NaN,Nicolas Chatelain,181 cm,70 kg
6,Competed in Olympic Games,Male,Patrick•Chila,Patrick•Chila,"27 November 1969 in Ris-Orangis, Essonne (FRA)",NaN,France,7,180 cm / 73 kg,"AS Pontoise-Cergy TT, Pontoise (FRA) / Royal V...",NaN,NaN,NaN,NaN,NaN,NaN,Patrick Chila,180 cm,73 kg
7,Competed in Olympic Games,Male,Henri Jean•Cochet,Henri•Cochet,"14 December 1901 in Villeurbanne, Rhône (FRA)","2 April 1987 in Saint-Germain-en-Laye, Yveline...",France,8,NaN,NaN,Le Magicien,NaN,NaN,NaN,NaN,NaN,Henri Cochet,NaN,NaN
8,Competed in Olympic Games,Male,Marcel•Cousin,Marcel•Cousin,"4 August 1896 in Nîmes, Gard (FRA)","1 August 1986 in Nîmes, Gard (FRA)",France,9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Marcel Cousin,NaN,NaN
9,Competed in Olympic Games,Male,Luc Henri Hervé Guy•Gardye de la Chapelle,Guy•de la Chapelle,"16 July 1868 in Farges-Allichamps, Cher (FRA)",27 August 1923,France,10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Guy de la Chapelle,NaN,NaN

### Now remove the units "cm" and "kg"

In [14]:
df['height_cm'] = pd.to_numeric(df['height_cm'].str.strip(' cm'), errors='coerce')
df['weight_kg'] = pd.to_numeric(df['weight_kg'].str.strip(' kg'), errors='coerce')

In [15]:
df.head(10)

,Roles,Sex,Full name,Used name,Born,Died,NOC,athlete_id,Measurements,Affiliations,Nick/petnames,Title(s),Other names,Nationality,Original name,Name order,name,height_cm,weight_kg
0,Competed in Olympic Games,Male,"François Joseph Marie Antoine ""Jean-François""•...",Jean-François•Blanchy,"12 December 1886 in Bordeaux, Gironde (FRA)","2 October 1960 in Saint-Jean-de-Luz, Pyrénées-...",France,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Jean-François Blanchy,NaN,NaN
1,Competed in Olympic Games,Male,Arnaud Benjamin•Boetsch,Arnaud•Boetsch,"1 April 1969 in Meulan, Yvelines (FRA)",NaN,France,2,183 cm / 76 kg,"Racing Club de France, Paris (FRA)",NaN,NaN,NaN,NaN,NaN,NaN,Arnaud Boetsch,183.0,76.0
2,Competed in Olympic Games • Administrator,Male,Jean Laurent Robert•Borotra,Jean•Borotra,"13 August 1898 in Biarritz, Pyrénées-Atlantiqu...","17 July 1994 in Arbonne, Pyrénées-Atlantiques ...",France,3,183 cm / 76 kg,"TCP, Paris (FRA)",Le Basque Bondissant (The Bounding Basque),NaN,NaN,NaN,NaN,NaN,Jean Borotra,183.0,76.0
3,Competed in Olympic Games,Male,Jacques Marie Stanislas Jean•Brugnon,Jacques•Brugnon,"11 May 1895 in Paris VIIIe, Paris (FRA)","20 March 1978 in Monaco, Monaco (MON)",France,4,168 cm / 64 kg,"Sporting club de Paris, Paris (FRA)",Toto,NaN,NaN,NaN,NaN,NaN,Jacques Brugnon,168.0,64.0
4,Competed in Olympic Games,Male,Henry Albert•Canet,Albert•Canet,"17 April 1878 in Wandsworth, England (GBR)","25 July 1930 in Paris VIIe, Paris (FRA)",France,5,NaN,"TCP, Paris (FRA)",NaN,NaN,NaN,NaN,NaN,NaN,Albert Canet,NaN,NaN
5,Competed in Olympic Games,Male,Nicolas•Chatelain,Nicolas•Chatelain,"13 January 1970 in Amiens, Somme (FRA)",NaN,France,6,181 cm / 70 kg,"SAG Cestas, Cestas (FRA)",NaN,NaN,NaN,NaN,NaN,NaN,Nicolas Chatelain,181.0,70.0
6,Competed in Olympic Games,Male,Patrick•Chila,Patrick•Chila,"27 November 1969 in Ris-Orangis, Essonne (FRA)",NaN,France,7,180 cm / 73 kg,"AS Pontoise-Cergy TT, Pontoise (FRA) / Royal V...",NaN,NaN,NaN,NaN,NaN,NaN,Patrick Chila,180.0,73.0
7,Competed in Olympic Games,Male,Henri Jean•Cochet,Henri•Cochet,"14 December 1901 in Villeurbanne, Rhône (FRA)","2 April 1987 in Saint-Germain-en-Laye, Yveline...",France,8,NaN,NaN,Le Magicien,NaN,NaN,NaN,NaN,NaN,Henri Cochet,NaN,NaN
8,Competed in Olympic Games,Male,Marcel•Cousin,Marcel•Cousin,"4 August 1896 in Nîmes, Gard (FRA)","1 August 1986 in Nîmes, Gard (FRA)",France,9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Marcel Cousin,NaN,NaN
9,Competed in Olympic Games,Male,Luc Henri Hervé Guy•Gardye de la Chapelle,Guy•de la Chapelle,"16 July 1868 in Farges-Allichamps, Cher (FRA)",27 August 1923,France,10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Guy de la Chapelle,NaN,NaN

### Task-03: Parse Out Dates from 'Born' and 'Died' columns

In [16]:
date_pattern = r'(\d+ \w+ \d{4}|\d{4}|\w+ \d{4})'
df['born_date'] = df['Born'].str.extract(date_pattern)
df['born_date'] = pd.to_datetime(df['born_date'], format="mixed", errors='coerce')

df['died_date'] = df['Died'].str.extract(date_pattern)
df['died_date'] = pd.to_datetime(df['died_date'], format="mixed", errors='coerce')

In [17]:
df.head()

,Roles,Sex,Full name,Used name,Born,Died,NOC,athlete_id,Measurements,Affiliations,...,Title(s),Other names,Nationality,Original name,Name order,name,height_cm,weight_kg,born_date,died_date
0,Competed in Olympic Games,Male,"François Joseph Marie Antoine ""Jean-François""•...",Jean-François•Blanchy,"12 December 1886 in Bordeaux, Gironde (FRA)","2 October 1960 in Saint-Jean-de-Luz, Pyrénées-...",France,1,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,Jean-François Blanchy,NaN,NaN,1886-12-12,1960-10-02
1,Competed in Olympic Games,Male,Arnaud Benjamin•Boetsch,Arnaud•Boetsch,"1 April 1969 in Meulan, Yvelines (FRA)",NaN,France,2,183 cm / 76 kg,"Racing Club de France, Paris (FRA)",...,NaN,NaN,NaN,NaN,NaN,Arnaud Boetsch,183.0,76.0,1969-04-01,NaT
2,Competed in Olympic Games • Administrator,Male,Jean Laurent Robert•Borotra,Jean•Borotra,"13 August 1898 in Biarritz, Pyrénées-Atlantiqu...","17 July 1994 in Arbonne, Pyrénées-Atlantiques ...",France,3,183 cm / 76 kg,"TCP, Paris (FRA)",...,NaN,NaN,NaN,NaN,NaN,Jean Borotra,183.0,76.0,1898-08-13,1994-07-17
3,Competed in Olympic Games,Male,Jacques Marie Stanislas Jean•Brugnon,Jacques•Brugnon,"11 May 1895 in Paris VIIIe, Paris (FRA)","20 March 1978 in Monaco, Monaco (MON)",France,4,168 cm / 64 kg,"Sporting club de Paris, Paris (FRA)",...,NaN,NaN,NaN,NaN,NaN,Jacques Brugnon,168.0,64.0,1895-05-11,1978-03-20
4,Competed in Olympic Games,Male,Henry Albert•Canet,Albert•Canet,"17 April 1878 in Wandsworth, England (GBR)","25 July 1930 in Paris VIIe, Paris (FRA)",France,5,NaN,"TCP, Paris (FRA)",...,NaN,NaN,NaN,NaN,NaN,Albert Canet,NaN,NaN,1878-04-17,1930-07-25

### Task-04: Parsing out location from Born Column

In [18]:
df['Born'].head()

0          12 December 1886 in Bordeaux, Gironde (FRA)
1               1 April 1969 in Meulan, Yvelines (FRA)
2    13 August 1898 in Biarritz, Pyrénées-Atlantiqu...
3              11 May 1895 in Paris VIIIe, Paris (FRA)
4           17 April 1878 in Wandsworth, England (GBR)
Name: Born, dtype: str

In [19]:
df[['location', 'country_code']] = df['Born'].str.extract(r'in (.*?) \((.*?)\)$')

In [20]:
df.head(10)

,Roles,Sex,Full name,Used name,Born,Died,NOC,athlete_id,Measurements,Affiliations,...,Nationality,Original name,Name order,name,height_cm,weight_kg,born_date,died_date,location,country_code
0,Competed in Olympic Games,Male,"François Joseph Marie Antoine ""Jean-François""•...",Jean-François•Blanchy,"12 December 1886 in Bordeaux, Gironde (FRA)","2 October 1960 in Saint-Jean-de-Luz, Pyrénées-...",France,1,NaN,NaN,...,NaN,NaN,NaN,Jean-François Blanchy,NaN,NaN,1886-12-12,1960-10-02,"Bordeaux, Gironde",FRA
1,Competed in Olympic Games,Male,Arnaud Benjamin•Boetsch,Arnaud•Boetsch,"1 April 1969 in Meulan, Yvelines (FRA)",NaN,France,2,183 cm / 76 kg,"Racing Club de France, Paris (FRA)",...,NaN,NaN,NaN,Arnaud Boetsch,183.0,76.0,1969-04-01,NaT,"Meulan, Yvelines",FRA
2,Competed in Olympic Games • Administrator,Male,Jean Laurent Robert•Borotra,Jean•Borotra,"13 August 1898 in Biarritz, Pyrénées-Atlantiqu...","17 July 1994 in Arbonne, Pyrénées-Atlantiques ...",France,3,183 cm / 76 kg,"TCP, Paris (FRA)",...,NaN,NaN,NaN,Jean Borotra,183.0,76.0,1898-08-13,1994-07-17,"Biarritz, Pyrénées-Atlantiques",FRA
3,Competed in Olympic Games,Male,Jacques Marie Stanislas Jean•Brugnon,Jacques•Brugnon,"11 May 1895 in Paris VIIIe, Paris (FRA)","20 March 1978 in Monaco, Monaco (MON)",France,4,168 cm / 64 kg,"Sporting club de Paris, Paris (FRA)",...,NaN,NaN,NaN,Jacques Brugnon,168.0,64.0,1895-05-11,1978-03-20,"Paris VIIIe, Paris",FRA
4,Competed in Olympic Games,Male,Henry Albert•Canet,Albert•Canet,"17 April 1878 in Wandsworth, England (GBR)","25 July 1930 in Paris VIIe, Paris (FRA)",France,5,NaN,"TCP, Paris (FRA)",...,NaN,NaN,NaN,Albert Canet,NaN,NaN,1878-04-17,1930-07-25,"Wandsworth, England",GBR
5,Competed in Olympic Games,Male,Nicolas•Chatelain,Nicolas•Chatelain,"13 January 1970 in Amiens, Somme (FRA)",NaN,France,6,181 cm / 70 kg,"SAG Cestas, Cestas (FRA)",...,NaN,NaN,NaN,Nicolas Chatelain,181.0,70.0,1970-01-13,NaT,"Amiens, Somme",FRA
6,Competed in Olympic Games,Male,Patrick•Chila,Patrick•Chila,"27 November 1969 in Ris-Orangis, Essonne (FRA)",NaN,France,7,180 cm / 73 kg,"AS Pontoise-Cergy TT, Pontoise (FRA) / Royal V...",...,NaN,NaN,NaN,Patrick Chila,180.0,73.0,1969-11-27,NaT,"Ris-Orangis, Essonne",FRA
7,Competed in Olympic Games,Male,Henri Jean•Cochet,Henri•Cochet,"14 December 1901 in Villeurbanne, Rhône (FRA)","2 April 1987 in Saint-Germain-en-Laye, Yveline...",France,8,NaN,NaN,...,NaN,NaN,NaN,Henri Cochet,NaN,NaN,1901-12-14,1987-04-02,"Villeurbanne, Rhône",FRA
8,Competed in Olympic Games,Male,Marcel•Cousin,Marcel•Cousin,"4 August 1896 in Nîmes, Gard (FRA)","1 August 1986 in Nîmes, Gard (FRA)",France,9,NaN,NaN,...,NaN,NaN,NaN,Marcel Cousin,NaN,NaN,1896-08-04,1986-08-01,"Nîmes, Gard",FRA
9,Competed in Olympic Games,Male,Luc Henri Hervé Guy•Gardye de la Chapelle,Guy•de la Chapelle,"16 July 1868 in Farges-Allichamps, Cher (FRA)",27 August 1923,France,10,NaN,NaN,...,NaN,NaN,NaN,Guy de la Chapelle,NaN,NaN,1868-07-16,1923-08-27,"Farges-Allichamps, Cher",FRA

### Task-05: Getting rid of extra columns

In [21]:
df.columns

Index(['Roles', 'Sex', 'Full name', 'Used name', 'Born', 'Died', 'NOC',
       'athlete_id', 'Measurements', 'Affiliations', 'Nick/petnames',
       'Title(s)', 'Other names', 'Nationality', 'Original name', 'Name order',
       'name', 'height_cm', 'weight_kg', 'born_date', 'died_date', 'location',
       'country_code'],
      dtype='str')

In [22]:
columns_needed = ['athlete_id', 'name', 'Sex', 'born_date', 'location', 'country_code', 'NOC', 'height_cm', 'weight_kg', 'died_date']

df_clean = df[columns_needed]

### Task-06: Converting all column names into snake case

In [25]:
df_clean.columns = df_clean.columns.str.lower().str.replace(" ", "_")

In [26]:
df_clean.head()

,athlete_id,name,sex,born_date,location,country_code,noc,height_cm,weight_kg,died_date
0,1,Jean-François Blanchy,Male,1886-12-12,"Bordeaux, Gironde",FRA,France,NaN,NaN,1960-10-02
1,2,Arnaud Boetsch,Male,1969-04-01,"Meulan, Yvelines",FRA,France,183.0,76.0,NaT
2,3,Jean Borotra,Male,1898-08-13,"Biarritz, Pyrénées-Atlantiques",FRA,France,183.0,76.0,1994-07-17
3,4,Jacques Brugnon,Male,1895-05-11,"Paris VIIIe, Paris",FRA,France,168.0,64.0,1978-03-20
4,5,Albert Canet,Male,1878-04-17,"Wandsworth, England",GBR,France,NaN,NaN,1930-07-25

In [27]:
df_clean.to_csv('./Cleaned_Data/cleaned_bios.csv', index=False)